//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsScoreManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Test_Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test_Student()
        {
            this.Test_TestInfo = new HashSet<Test_TestInfo>();
        }
    
        public int Id { get; set; }
        public Nullable<int> StructureId { get; set; }
        public string StudentNum { get; set; }
        public string Name { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual Test_SchoolStructure Test_SchoolStructure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_TestInfo> Test_TestInfo { get; set; }
    }
}
