//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsScoreManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_TestInfo
    {
        public int TestId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual Test_Student Test_Student { get; set; }
        public virtual Test_Subject Test_Subject { get; set; }
    }
}
