//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsScoreManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_SchoolStructure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test_SchoolStructure()
        {
            this.Test_Student = new HashSet<Test_Student>();
        }
    
        public int StructureId { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<int> Class { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_Student> Test_Student { get; set; }
    }
}
